import './globals.css';
import { Heebo } from 'next/font/google';

const heebo = Heebo({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${heebo.className} bg-gradient-to-r from-[#935FD3] to-[#9245f1]`}>{children}</body>
    </html>
  )
}
